{
    'name': 'Performance Audit',
    'version': '1.0',
    'summary': 'Gather information about possible performance degradation',
    'category': 'Tools',
    'author': 'kasm',
    'license': 'LGPL-3',
    'depends': ['base', 'web', 'base_automation'],
    "icon": "performance_audit/static/description/icon.png",
    'data': [
        'security/ir.model.access.csv',
        'wizard/performance_audit_wizard.xml',
        'wizard/field_trigger_tree_wizard.xml',
        'views/slow_filter_views.xml',
        'views/automation_audit_views.xml',
        'views/slow_request_views.xml',
        'views/cron_audit_views.xml',
        'views/table_size_views.xml',
        'views/performance_audit_dashboard.xml',
        'views/performance_menu.xml',
    ],
    'installable': True,
    'application': True,
    'assets': {
        'web.assets_backend': [
            'performance_audit/static/src/xml/slow_filter_templates.xml',
            'performance_audit/static/src/xml/dashboard.xml',
            'performance_audit/static/src/xml/field_trigger_tree.xml',
            'performance_audit/static/src/xml/slow_request_timeline.xml',
            'performance_audit/static/src/js/slow_filter_audit.js',
            'performance_audit/static/src/js/dashboard.js',
            'performance_audit/static/src/js/field_trigger_tree.js',
            'performance_audit/static/src/js/slow_request_timeline.js',
            'performance_audit/static/src/scss/field_trigger_tree.scss',
            'performance_audit/static/src/scss/slow_request_timeline.scss',
        ],
    },
}
